### ISSUE TITLE
NaN to float failed

### ISSUE THREAD

**Issue by bgruening** [maxplanck-ie/HiCExplorer#80]
Encountered on my work on the develop branch.

```
|  processing chromosome chrM
|  /home/bag/miniconda3/envs/mulled-v1-9edb84bafdd4afcd296070604e305ff8b4927b823b3b2fdf9db528a123d76d21/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
|  out=out, **kwargs)
|  /home/bag/miniconda3/envs/mulled-v1-9edb84bafdd4afcd296070604e305ff8b4927b823b3b2fdf9db528a123d76d21/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
|  ret = ret.dtype.type(ret / rcount)
|  Traceback (most recent call last):
|  File "/home/bag/miniconda3/envs/mulled-v1-9edb84bafdd4afcd296070604e305ff8b4927b823b3b2fdf9db528a123d76d21/bin/hicPlotDistVsCounts", line 7, in <module>
|  main()
|  File "/home/bag/.local/lib/python2.7/site-packages/hicexplorer/hicPlotDistVsCounts.py", line 303, in main
|  mean_dict[matrix_file] = compute_distance_mean(hic_ma, maxdepth=args.maxdepth, perchr=args.perchr)
|  File "/home/bag/.local/lib/python2.7/site-packages/hicexplorer/hicPlotDistVsCounts.py", line 197, in compute_distance_mean
|  HiCMatrix.hiCMatrix.fit_cut_intervals(cut_intervals[chrname]))
|  File "/home/bag/.local/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 458, in fit_cut_intervals
|  median = int(np.median(np.diff(start)))
|  ValueError: cannot convert float NaN to integer
```

**Comment by fidelram** [comment]
which sample data were you using? the small test data ?

**Comment by bgruening** [comment]
Yes, `small_test_matrix_50kb_res.h5`.

**Comment by fidelram** [comment]
commit d423f0abefe241fb73e53c870cddff82ebb782bc should solve the problem.
